In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ratings-preproc/data_train.csv
/kaggle/input/ratings-preproc/data_test.csv

In [2]:
import pandas as pd

df_test = pd.read_csv('/kaggle/input/ratings-preproc/data_test.csv')
df_train = pd.read_csv('/kaggle/input/ratings-preproc/data_train.csv')

In [3]:
print(len(df_test))
df_test.head()

10000

   uid   mid  rating
0  598   502     4.5
1  471  6950     3.0
2   20  2235     3.0
3  528  7147     3.0
4  623   216     4.0

In [4]:
print(len(df_train))
df_train.head()

90004

   uid   mid  rating
0  462   214     4.0
1  638  2275     3.0
2  310  2452     3.5
3  319  1654     4.0
4  119   270     3.5

loading to nmpy arrays

In [5]:
uid_train = df_train["uid"].to_numpy()
print(uid_train)
mid_train = df_train["mid"].to_numpy()
print(mid_train)

[462 638 310 ... 265  43 467]
[ 214 2275 2452 ...   64  453 2526]

In [6]:
uid_test = df_test["uid"].to_numpy()
print(uid_test)
mid_test = df_test["mid"].to_numpy()
print(mid_test)

[598 471  20 ... 212 344 212]
[ 502 6950 2235 ... 4181  278 5420]

# UA and IA (step 1)

In [8]:
df_train = df_train.loc[(df_train!=0).any(axis=1)] #did nothing, wanted to eliminate all 0 ratings- non existent ratings

In [9]:
!pip install scikit-learn==0.24

Collecting scikit-learn==0.24
  Downloading scikit-learn-0.24.0.tar.gz (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 50.6 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==0.24) (1.26.4)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==0.24) (1.15.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==0.24) (1.5.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==0.24) (3.6.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.13.3->scikit-learn==0.24) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.13.3->scikit-learn==0.24) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.13.3->scikit-learn==0.24) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.13.3->scikit-learn==0.24) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.13.3->scikit-learn==0.24) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.13.3->scikit-learn==0.24) (2.4.1)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.13.3->scikit-learn==0.24) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.13.3->scikit-learn==0.24) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.13.3->scikit-learn==0.24) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.13.3->scikit-learn==0.24) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.13.3->scikit-learn==0.24) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.13.3->scikit-learn==0.24) (2024.2.0)
Building wheels for collected packages: scikit-learn
  error: subprocess-exited-with-error

  × Building wheel for scikit-learn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for scikit-learn (pyproject.toml) ... error
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (scikit-learn)

In [9]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn) (2.4.1)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.17.3->scikit-learn) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.17.3->scikit-learn) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.17.3->scikit-learn) (2024.2.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import pandas as pd
import numpy as np
from sklearn.metrics import root_mean_squared_error

# train and test dataframes assumed to have columns: userId, movieId, rating

# === 1. Compute user averages ===
user_mean = df_train.groupby("uid")["rating"].mean()

# === 2. Compute movie averages ===
movie_mean = df_train.groupby("mid")["rating"].mean()

# === 3. Global mean (backup if user/movie not in train set)
global_mean = df_train["rating"].mean()

# ---------------------------------------------
# User Average Predictions
# ---------------------------------------------
ua_pred = df_test["uid"].map(user_mean)    # maps user to mean rating
ua_pred = ua_pred.fillna(global_mean)      # in case user not in train

# RMSE UA
rmse_ua = root_mean_squared_error(df_test["rating"], ua_pred)


# ---------------------------------------------
# Item Average Predictions
# ---------------------------------------------
ia_pred = df_test["mid"].map(movie_mean)  # maps movie to mean rating
ia_pred = ia_pred.fillna(global_mean)      # in case movie not in train

# RMSE IA
rmse_ia = root_mean_squared_error(df_test["rating"], ia_pred)


print("RMSE User Average:", rmse_ua)
print("RMSE Item Average:", rmse_ia)

ImportError: cannot import name 'root_mean_squared_error' from 'sklearn.metrics' (/usr/local/lib/python3.11/dist-packages/sklearn/metrics/__init__.py)

In [ ]:
print(len(df_train))

In [ ]:
df_test = df_test.loc[(df_test!=0).any(axis=1)]

In [ ]:
print(len(df_test))

# SVD (step 2)

# UCF (step 4)

# evalutaion algorithm comparissons (step 5)